development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: poker_hands_development
  pool: 5
  username: root
  password: 
  
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: poker_hands_production
  pool: 5
  username: root
  password: 
